name: Build executable

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Install dependencies
      run: go mod tidy

    - name: Build Go executable
      run: |
        GOOS=${{ matrix.os }} GOARCH=amd64 go build -ldflags "-X main.domainName=${{ secrets.DOMAINNAME }}" -o dns-${{ matrix.os }}-amd64

    - name: Rename executable (if Windows)
      if: matrix.os == 'windows'
      run: mv dns-windows-amd64 dns-windows-amd64.exe

    - name: Upload Windows executable (if Windows)
      if: matrix.os == 'windows'
      uses: actions/upload-artifact@v4
      with:
        name: dns-windows
        path: dns-windows-amd64.exe

    - name: Upload Linux executable (if Linux)
      if: matrix.os == 'linux'
      uses: actions/upload-artifact@v4
      with:
        name: dns-linux
        path: dns-linux-amd64