name: Build executable

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Build executable
      shell: bash
      env:
        DOMAIN_NAME: ${{ secrets.domainName }}
      run: go build -ldflags "-X main.domainName=$DOMAIN_NAME" -o dns.out

    - name: Archive dns go executables
      uses: actions/upload-artifact@v4
      with:
        name: dns
        path: |
          dns.out
